[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list",
    "echo 'deb [arch=arm64] http://ports.ubuntu.com/ focal main restricted universe' >> /etc/apt/sources.list",
    "echo 'deb [arch=arm64] http://ports.ubuntu.com/ focal-updates main restricted universe' >> /etc/apt/sources.list",
    "apt-get update",
    "apt-get install -y libasound2-dev:arm64",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["PKG_CONFIG_PATH", "PKG_CONFIG_ALLOW_CROSS"]
