name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CRATE_NAME: miditui

jobs:
  crates_io_publish:
    name: Crates.io Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Publish to Crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  build_binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux
            # must be a public GitHub repository
          - os: ubuntu-24.04-arm
            suffix: linux-arm64
          - os: macos-15-intel
            suffix: macos-intel
          - os: macos-latest
            suffix: macos-arm
          - os: windows-latest
            suffix: windows
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Disable Windows Defender (speed up build)
        if: runner.os == 'Windows'
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Build Binary
        env:
          CARGO_INCREMENTAL: 0
        run: cargo build --release

      - name: Package binary (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x "target/release/${CRATE_NAME}"
          tar -czvf "${CRATE_NAME}-${{ matrix.suffix }}.tar.gz" -C target/release "${CRATE_NAME}"

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path "target/release/${env:CRATE_NAME}.exe" -DestinationPath "${env:CRATE_NAME}-${{ matrix.suffix }}.zip"
        shell: powershell

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.CRATE_NAME }}-${{ matrix.suffix }}${{ runner.os == 'Windows' && '.zip' || '.tar.gz' }}
