name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CRATE_NAME: miditui

jobs:
  crates_io_publish:
    name: Crates.io Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Publish to Crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  build_binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux
          # For ARM Linux, we use cross to build the binary: the Linux ARM toolchains
          # are not available for private repos, so cross provides a workaround
          - os: ubuntu-latest
            suffix: linux-arm64
            target: aarch64-unknown-linux-gnu
            use_cross: true
          - os: macos-15-intel
            suffix: macos-intel
          - os: macos-latest
            suffix: macos-arm
          - os: windows-latest
            suffix: windows
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux' && !matrix.use_cross
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Disable Windows Defender (speed up build)
        if: runner.os == 'Windows'
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Build Binary
        env:
          CARGO_INCREMENTAL: 0
        run: ${{ matrix.use_cross && format('cross build --release --target {0}', matrix.target) || 'cargo build --release' }}

      - name: Rename binary
        shell: bash
        run: |
          ext=${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          src=${{ matrix.use_cross && format('target/{0}/release', matrix.target) || 'target/release' }}
          cp "${src}/${CRATE_NAME}${ext}" "${CRATE_NAME}-${{ matrix.suffix }}${ext}"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.CRATE_NAME }}-${{ matrix.suffix }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
